// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: DoughProoferDisplay

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_tempPanel;
extern lv_obj_t *ui_temperatureLabel;
extern lv_obj_t *ui_humidityPanel;
extern lv_obj_t *ui_humidityLabel;
extern lv_obj_t *ui_operationsPanel;
extern void ui_event_delayStart( lv_event_t * e);
extern lv_obj_t *ui_delayStart;
extern lv_obj_t *ui_delayStartLabel;
extern lv_obj_t *ui_delayStartAmount;
extern lv_obj_t *ui_proofTypeLabel;
extern lv_obj_t *ui_proofType;
extern lv_obj_t *ui_TemperatureValue;
extern lv_obj_t *ui_humidity;
extern lv_obj_t *ui_LightsOn;
extern lv_obj_t *ui_LightsLabel;
extern lv_obj_t *ui_startButton;
extern lv_obj_t *ui_startButtonLabel;
extern lv_obj_t *ui_VersionInfo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
