// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: DoughProoferDisplay

#include "ui.h"

lv_obj_t *ui_Screen1;
lv_obj_t *ui_tempPanel;
lv_obj_t *ui_temperatureLabel;
lv_obj_t *ui_humidityPanel;
lv_obj_t *ui_humidityLabel;
lv_obj_t *ui_operationsPanel;
lv_obj_t *ui_delayStart;
lv_obj_t *ui_delayStartLabel;
lv_obj_t *ui_delayStartAmount;
lv_obj_t *ui_proofTypeLabel;
lv_obj_t *ui_proofType;
lv_obj_t *ui_TemperatureValue;
lv_obj_t *ui_humidity;
lv_obj_t *ui_LightsOn;
lv_obj_t *ui_LightsLabel;
lv_obj_t *ui_startButton;
lv_obj_t *ui_startButtonLabel;
lv_obj_t *ui_VersionInfo;

// event funtions
void ui_event_delayStart( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_dropdown_set_property(ui_delayStartAmount, _UI_DROPDOWN_PROPERTY_SELECTED, 1);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x9BBFD3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_tempPanel, 458);
lv_obj_set_height( ui_tempPanel, 361);
lv_obj_set_x( ui_tempPanel, 0 );
lv_obj_set_y( ui_tempPanel, -207 );
lv_obj_set_align( ui_tempPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_tempPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_tempPanel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_tempPanel, lv_color_hex(0x509BF2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tempPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_tempPanel, lv_color_hex(0x0420BA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_tempPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_tempPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_tempPanel, lv_color_hex(0x2400FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tempPanel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temperatureLabel = lv_label_create(ui_tempPanel);
lv_obj_set_width( ui_temperatureLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temperatureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temperatureLabel, -133 );
lv_obj_set_y( ui_temperatureLabel, -156 );
lv_obj_set_align( ui_temperatureLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperatureLabel,"Temperature");
lv_obj_set_style_text_color(ui_temperatureLabel, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temperatureLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temperatureLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidityPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_humidityPanel, 204);
lv_obj_set_height( ui_humidityPanel, 204);
lv_obj_set_x( ui_humidityPanel, -122 );
lv_obj_set_y( ui_humidityPanel, 92 );
lv_obj_set_align( ui_humidityPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_humidityPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_humidityPanel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_humidityPanel, lv_color_hex(0x5299F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_humidityPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_humidityPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_humidityPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_humidityPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidityLabel = lv_label_create(ui_humidityPanel);
lv_obj_set_width( ui_humidityLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidityLabel, -32 );
lv_obj_set_y( ui_humidityLabel, -81 );
lv_obj_set_align( ui_humidityLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidityLabel,"Humidity");
lv_obj_set_style_text_font(ui_humidityLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_operationsPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_operationsPanel, 226);
lv_obj_set_height( ui_operationsPanel, 250);
lv_obj_set_x( ui_operationsPanel, 108 );
lv_obj_set_y( ui_operationsPanel, 114 );
lv_obj_set_align( ui_operationsPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_operationsPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_operationsPanel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_operationsPanel, lv_color_hex(0x5299F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_operationsPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_operationsPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_operationsPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_operationsPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_delayStart = lv_switch_create(ui_operationsPanel);
lv_obj_set_width( ui_delayStart, 50);
lv_obj_set_height( ui_delayStart, 25);
lv_obj_set_x( ui_delayStart, -70 );
lv_obj_set_y( ui_delayStart, 2 );
lv_obj_set_align( ui_delayStart, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_delayStart, lv_color_hex(0x9CBED5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_delayStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_delayStart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_delayStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_delayStart, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_delayStart, lv_color_hex(0x0A02F8), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_delayStart, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_delayStartLabel = lv_label_create(ui_operationsPanel);
lv_obj_set_width( ui_delayStartLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_delayStartLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_delayStartLabel, 28 );
lv_obj_set_y( ui_delayStartLabel, 2 );
lv_obj_set_align( ui_delayStartLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_delayStartLabel,"Delay Start");
lv_obj_set_style_text_font(ui_delayStartLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_delayStartAmount = lv_dropdown_create(ui_Screen1);
lv_dropdown_set_options( ui_delayStartAmount, "30 min\n60 min\n90 min\n120 min" );
lv_dropdown_set_dir( ui_delayStartAmount, LV_DIR_BOTTOM );
lv_dropdown_set_symbol( ui_delayStartAmount, LV_SYMBOL_DOWN );
lv_obj_set_width( ui_delayStartAmount, 135);
lv_obj_set_height( ui_delayStartAmount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_delayStartAmount, 108 );
lv_obj_set_y( ui_delayStartAmount, 158 );
lv_obj_set_align( ui_delayStartAmount, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_delayStartAmount, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_add_flag( ui_delayStartAmount, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_delayStartAmount, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_delayStartAmount, lv_color_hex(0x9CBED5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_delayStartAmount, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_proofTypeLabel = lv_label_create(ui_operationsPanel);
lv_obj_set_width( ui_proofTypeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_proofTypeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_proofTypeLabel, 0 );
lv_obj_set_y( ui_proofTypeLabel, -99 );
lv_obj_set_align( ui_proofTypeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_proofTypeLabel,"Proof Type");
lv_obj_set_style_text_font(ui_proofTypeLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_proofType = lv_dropdown_create(ui_Screen1);
lv_dropdown_set_options( ui_proofType, "Bread\nCroissant" );
lv_dropdown_set_dir( ui_proofType, LV_DIR_BOTTOM );
lv_dropdown_set_symbol( ui_proofType, LV_SYMBOL_DOWN );
lv_obj_set_width( ui_proofType, 160);
lv_obj_set_height( ui_proofType, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_proofType, 108 );
lv_obj_set_y( ui_proofType, 58 );
lv_obj_set_align( ui_proofType, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_proofType, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_add_flag( ui_proofType, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_proofType, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_proofType, lv_color_hex(0x9CBED5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_proofType, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_TemperatureValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue, 5 );
lv_obj_set_y( ui_TemperatureValue, -165 );
lv_obj_set_align( ui_TemperatureValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue,"93");
lv_obj_set_style_text_color(ui_TemperatureValue, lv_color_hex(0x9ED6FC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_TemperatureValue, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue, &ui_font_Bod300, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_humidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity, -117 );
lv_obj_set_y( ui_humidity, 102 );
lv_obj_set_align( ui_humidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity,"85%");
lv_obj_set_style_text_color(ui_humidity, lv_color_hex(0x9CD6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_humidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_humidity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_humidity, &ui_font_Bod86, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightsOn = lv_switch_create(ui_operationsPanel);
lv_obj_set_width( ui_LightsOn, 50);
lv_obj_set_height( ui_LightsOn, 25);
lv_obj_set_x( ui_LightsOn, -70 );
lv_obj_set_y( ui_LightsOn, 94 );
lv_obj_set_align( ui_LightsOn, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_LightsOn, lv_color_hex(0x9CBED5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightsOn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LightsOn, lv_color_hex(0x0800FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightsOn, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LightsLabel = lv_label_create(ui_operationsPanel);
lv_obj_set_width( ui_LightsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightsLabel, 5 );
lv_obj_set_y( ui_LightsLabel, 95 );
lv_obj_set_align( ui_LightsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LightsLabel,"Lights");
lv_obj_set_style_text_font(ui_LightsLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_startButton = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_startButton, 249);
lv_obj_set_height( ui_startButton, 92);
lv_obj_set_x( ui_startButton, -10 );
lv_obj_set_y( ui_startButton, 306 );
lv_obj_set_align( ui_startButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_startButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_startButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_startButton, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_startButton, lv_color_hex(0x2304F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_startButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_startButtonLabel = lv_label_create(ui_startButton);
lv_obj_set_width( ui_startButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_startButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_startButtonLabel, -1 );
lv_obj_set_y( ui_startButtonLabel, 6 );
lv_obj_set_align( ui_startButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_startButtonLabel,"Start!");
lv_obj_set_style_text_color(ui_startButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_startButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_startButtonLabel, &ui_font_Bod86, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VersionInfo = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_VersionInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VersionInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VersionInfo, 0 );
lv_obj_set_y( ui_VersionInfo, 383 );
lv_obj_set_align( ui_VersionInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_VersionInfo,"Rainbird Baking V.1.3 - May 2026");

lv_obj_clear_flag(ui_tempPanel, LV_OBJ_FLAG_CLICKABLE);
lv_obj_clear_flag(ui_humidityPanel, LV_OBJ_FLAG_CLICKABLE);
lv_obj_clear_flag(ui_operationsPanel, LV_OBJ_FLAG_CLICKABLE);
lv_obj_clear_flag(ui_temperatureLabel, LV_OBJ_FLAG_CLICKABLE);
lv_obj_clear_flag(ui_humidityLabel, LV_OBJ_FLAG_CLICKABLE);
lv_obj_clear_flag(ui_delayStartLabel, LV_OBJ_FLAG_CLICKABLE);
lv_obj_clear_flag(ui_proofTypeLabel, LV_OBJ_FLAG_CLICKABLE);
lv_obj_clear_flag(ui_LightsLabel, LV_OBJ_FLAG_CLICKABLE);
lv_obj_clear_flag(ui_VersionInfo, LV_OBJ_FLAG_CLICKABLE);
lv_obj_move_foreground(ui_operationsPanel);
lv_obj_move_foreground(ui_delayStartAmount);
lv_obj_move_foreground(ui_proofType);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_tempPanel= NULL;
ui_temperatureLabel= NULL;
ui_humidityPanel= NULL;
ui_humidityLabel= NULL;
ui_operationsPanel= NULL;
ui_delayStart= NULL;
ui_delayStartLabel= NULL;
ui_delayStartAmount= NULL;
ui_proofTypeLabel= NULL;
ui_proofType= NULL;
ui_TemperatureValue= NULL;
ui_humidity= NULL;
ui_LightsOn= NULL;
ui_LightsLabel= NULL;
ui_startButton= NULL;
ui_startButtonLabel= NULL;
ui_VersionInfo= NULL;

}
